apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-cd-app
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd-image-updater.argoproj.io/git-repository: git@github.com:nagarajurahul/helm-charts.git
    argocd-image-updater.argoproj.io/image-list: image=nagarajurahul/rahul-repos:latest
    argocd-image-updater.argoproj.io/image.helm.image.repository: image.name
    argocd-image-updater.argoproj.io/image.helm.image.tag: image.tag
    argocd-image-updater.argoproj.io/image.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/github-ssh-creds
    argocd-image-updater.argoproj.io/write-back-target-branch: main
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ci-cd-app
  source:
    repoURL: https://github.com/nagarajurahul/helm-charts
    targetRevision: main
    path: ci-cd-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
