apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: business-apps
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  generators:
    - git:
        repoURL: https://github.com/nagarajurahul/gitops-apps
        revision: main
        files:
          - path: config/placement.yaml
  template:
    metadata:
      name: "{{app}}-{{cluster}}"
    spec:
      project: apps
      destination:
        name: "{{cluster}}"
        namespace: "{{namespace}}"
      source:
        repoURL: https://github.com/nagarajurahul/helm-charts
        targetRevision: main
        path: "{{app}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
