apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: business-apps
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  generators:
    - git:
        repoURL: https://github.com/nagarajurahul/gitops-apps
        revision: main
        files:
          - path: config/placement.yaml
  template:
    metadata:
      name: "{{app}}-{{cluster}}"
      labels: 
        app.kubernetes.io/managed-by: argocd 
        app.kubernetes.io/cluster: "{{cluster}}"
      annotations: 
        argocd.argoproj.io/sync-wave: "{{syncWave}}"
    spec:
      project: apps
      destination:
        name: "{{cluster}}"
        namespace: "{{namespace}}"
      source:
        repoURL: https://github.com/nagarajurahul/helm-charts
        targetRevision: main
        path: "{{helmLocation}}"
        helm: 
          # if you dont set releaseName explicitly
          # Your Argo CD Application name = Helm release name
          # Helm sees that the release name contains the chart name
          # Helm chooses .Release.Name as the resource name
          # Hence, you can change it, if needed
          # releaseName: "{{app}}"
          values: | 
            fullnameOverride: "{{app}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true 
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
