apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quotes-app-nodejs
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
  annotations:
    
spec:
  destination:
    namespace: quotes-app-nodejs
    server: https://kubernetes.default.svc
  project: default
  source:
    path: quotes-app-nodejs
    repoURL: https://github.com/nagarajurahul/helm-charts
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
