# gitops-apps/config/placement.yaml 
- app: quotes-app-nodejs
  namespace: quotes-app-nodejs
  helmLocation: quotes-app-nodejs
  syncWave: 60
  env: prod
  cluster: in-cluster #us-east-1-prod
- app: ci-cd-app
  namespace: ci-cd-app
  helmLocation: ci-cd-app
  syncWave: 60
  env: prod
  cluster: in-cluster #us-east-1-prod
- app: goflights
  namespace: goflights
  helmLocation: goflights
  syncWave: 60
  env: prod
  cluster: in-cluster #us-east-1-prod
- app: sql
  namespace: db
  helmLocation: sql
  syncWave: 50
  env: prod
  cluster: in-cluster #us-east-1-prod
